---

- name: aptbook
  hosts: all
  tasks:
   - name: Update repositories cache
     apt:
       update_cache: yes
   - name: Install packages
     apt:
       pkg:
       - git
       - packit
       - iptables
       - iptables-persistent
